# Definiciones de construcción: el Pipeline y la identidad que lo ejecuta.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constructor-serviceaccount.yaml
  - constructor-rolebinding.yaml
  - construir-y-publicar-pipeline.yaml
