# Gateway compartido de la plataforma y sus políticas transversales.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-gateway

resources:
  - namespace.yaml
  - gateway.yaml
  - shared-gateway-tlspolicy.yaml
  - shared-gateway-authpolicy.yaml
